import { Habit, HabitTemplate } from '../types/habit';

export const STORAGE_KEY = 'habitty.v1';

export const NOTIFICATION_STORAGE_KEY = 'habitty.notificationMap.v1';

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'habit-water',
    name: 'Drink Water',
    category: 'Health',
    frequency: 'daily',
    taskType: 'yesNo',
    taskColor: '#22c55e',
    reminderEnabled: true,
    reminderTime: '07:00',
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    createdAt: Date.now(),
  },
  {
    id: 'habit-workout',
    name: 'Workout',
    category: 'Fitness',
    frequency: 'daily',
    taskType: 'yesNo',
    taskColor: '#22c55e',
    reminderEnabled: true,
    reminderTime: '18:30',
    repeatDays: [1, 3, 5],
    createdAt: Date.now(),
  },
  {
    id: 'habit-read',
    name: 'Read 20 min',
    category: 'Learning',
    frequency: 'daily',
    taskType: 'yesNo',
    taskColor: '#f97316',
    reminderEnabled: true,
    reminderTime: '21:00',
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    createdAt: Date.now(),
  },
];

export const DAY_OPTIONS = [
  { label: 'M', value: 1 },
  { label: 'T', value: 2 },
  { label: 'W', value: 3 },
  { label: 'T', value: 4 },
  { label: 'F', value: 5 },
  { label: 'S', value: 6 },
  { label: 'S', value: 0 },
] as const;

export const HABIT_LIBRARY_TEMPLATES: HabitTemplate[] = [
  {
    id: 'drink-water',
    name: 'Drink Water',
    category: 'Health',
    frequency: 'daily',
    taskType: 'target',
    taskColor: '#0ea5e9',
    targetValue: 8,
    measurableUnit: 'glasses',
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    featured: true,
    tags: ['recommended', 'hydration', 'community-favorite'],
  },
  {
    id: 'morning-workout',
    name: 'Morning Workout',
    category: 'Fitness',
    frequency: 'daily',
    taskType: 'yesNo',
    taskColor: '#ef4444',
    repeatDays: [1, 2, 3, 4, 5],
    featured: true,
    tags: ['featured', 'fitness'],
  },
  {
    id: 'read-daily',
    name: 'Read 20 Minutes',
    category: 'Learning',
    frequency: 'daily',
    taskType: 'yesNo',
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    featured: true,
    tags: ['recommended', 'learning'],
  },
  {
    id: 'gratitude-journal',
    name: 'Gratitude Journal',
    category: 'Mental Wellness',
    frequency: 'daily',
    taskType: 'yesNo',
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    tags: ['mental wellness'],
  },
  {
    id: 'budget-check',
    name: 'Budget Check-in',
    category: 'Finance',
    frequency: 'daily',
    taskType: 'yesNo',
    repeatDays: [0],
    tags: ['finance', 'weekly'],
  },
  {
    id: 'deep-work',
    name: 'Deep Work Block',
    category: 'Productivity',
    frequency: 'daily',
    taskType: 'target',
    targetValue: 90,
    measurableUnit: 'minutes',
    repeatDays: [1, 2, 3, 4, 5],
    featured: true,
    tags: ['productivity', 'focus'],
  },
  {
    id: 'sleep-tracker',
    name: 'Sleep Tracker',
    category: 'Health',
    frequency: 'daily',
    taskType: 'target',
    targetValue: 8,
    measurableUnit: 'hours',
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    tags: ['health', 'sleep'],
  },
  {
    id: 'screen-time',
    name: 'Screen Time Limit',
    category: 'Productivity',
    frequency: 'daily',
    taskType: 'target',
    targetValue: 2,
    measurableUnit: 'hours',
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    tags: ['screen time', 'limits'],
  },
  {
    id: 'daily-expenses',
    name: 'Daily Expenses',
    category: 'Finance',
    frequency: 'daily',
    taskType: 'tracker',
    measurableUnit: '₹',
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    tags: ['finance', 'spending', 'tracker'],
  },
  {
    id: 'daily-mood',
    name: 'Mood Check-in',
    category: 'Wellness',
    frequency: 'daily',
    taskType: 'tracker',
    measurableUnit: 'score',
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    tags: ['wellness', 'mood', 'tracker'],
  },
  {
    id: 'morning-exercise',
    name: 'Morning Exercise',
    category: 'Fitness',
    frequency: 'daily',
    taskType: 'choice',
    choiceOptions: [
      { id: 'walk-30', name: 'Walk 30 minutes' },
      { id: 'cycle-20', name: 'Cycle 20 minutes' },
      { id: 'gym', name: 'Go to the Gym' },
    ],
    randomSuggestionEnabled: true,
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    tags: ['exercise', 'fitness', 'choose-any'],
  },
  {
    id: 'meal-plan',
    name: 'Healthy Meal',
    category: 'Health',
    frequency: 'daily',
    taskType: 'choice',
    choiceOptions: [
      { id: 'salad-bowl', name: 'Have a salad bowl' },
      { id: 'smoothie', name: 'Drink a smoothie' },
      { id: 'cooked-meal', name: 'Cook a healthy meal' },
    ],
    randomSuggestionEnabled: true,
    repeatDays: [1, 2, 3, 4, 5, 6, 0],
    tags: ['nutrition', 'health', 'choose-any'],
  },
];
